### ISSUE TITLE
Save profile data in mongodb

### ISSUE THREAD

**Issue by damianmarti** [moonshotcollective/recruiter.party#13]
When the user save your profile, the profile data should be saved in ceramic AND in our mongodb, using the GraphQL API.

**Comment by brentmartin** [comment]
✅ data is saved in ceramic

**Comment by damianmarti** [comment]
We should unify the ceramic and mongodb schema when doing it.

**Comment by damianmarti** [comment]
@QEDK if you didn't started with it, I can work on it today!
