### ISSUE TITLE
Fix multiple message signs

### ISSUE THREAD

**Issue by QEDK** [moonshotcollective/recruiter.party#31]
We don't need to have the users sign again and again when cookie is persisting.

**Comment by damianmarti** [comment]
We only ask now for user sign at wallet connect, so the user shouldn't get multiple sign messages. Do you see this behavior on the new code?

**Comment by QEDK** [comment]
> We only ask now for user sign at wallet connect, so the user shouldn't get multiple sign messages. Do you see this behavior on the new code?

We can make it even more scarce using some logic, I am working on it atm
