### ISSUE TITLE
Add Education fields

### ISSUE THREAD

**Issue by damianmarti** [moonshotcollective/recruiter.party#37]
Add new education fields on Ceramic and on the edit public profile.

The fields are:

- Title
- School or Institution 
- Start date (should be able to set a month/year or just a year)
- End date (should be able to set a month/year or just a year)
- Description

All fields are optional.

**Comment by Nazeeh21** [comment]
Can I work on this one also if it has same thing to do like #36?

**Comment by damianmarti** [comment]
@Nazeeh21 assigned! Thanks!!
