### ISSUE TITLE
Copy existing ceramic profiles to Mongo

### ISSUE THREAD

**Issue by damianmarti** [moonshotcollective/recruiter.party#41]
Create a script that copy the data from existing ceramic profiles to our backend on mongoDB. The script should add the new profile and update the existing ones.

**Comment by Dhaiwat10** [comment]
Where can we get the ceramic profiles from? Is there an endpoint?

**Comment by damianmarti** [comment]
We have to get the token ids from the contract and then get the uri for each tokenId using the uri method from the contract, extract the did from the uri and then query Ceramic to get the profiles data for that did.

Is almost the same that we do on the home page now.

**Comment by Dhaiwat10** [comment]
No promises but will give this a go! :)
