### ISSUE TITLE
Review profile creation flow

### ISSUE THREAD

**Issue by damianmarti** [moonshotcollective/recruiter.party#46]
Now the mint for the developer token is done on the editPrivateProfile, but this is the last step on the edit profile flow. 

Maybe, we should set the editPrivateProfile as the first step or think about another options.

**Comment by Nazeeh21** [comment]
I'm changing the workflow to edit the profile. I'm updating the workflow as Private Profile ->  Public Profile -> Basic Profile. If I've to make any other change or alter any other thing to let me know here

**Comment by damianmarti** [comment]
@Nazeeh21 this sounds good. I'm not sure if we should change something else, please let me know if you find something else to keep in mind for this change.

**Comment by Nazeeh21** [comment]
I had a few doubts and I dm you on discord, so can you please check that.
