### ISSUE TITLE
Be able to edit a section profile

### ISSUE THREAD

**Issue by damianmarti** [moonshotcollective/recruiter.party#56]
Without the user need to save the previous profile sections.

This is just for edit. A new user needs to save your private profile first.

**Comment by Nazeeh21** [comment]
@damianmarti To fix this issue I'm planning to display 3 buttons to the users whose private profile already exists. 
- For the existing user whose private profile exists, we'll display 3 buttons: `Back`, `Save`, and `Next`
- For the new user whose private profile data doesn't exist, we'll display 2 buttons: `Back` and `Save`

**Comment by damianmarti** [comment]
@Nazeeh21 yes! I think that we only need to do something different for a user whose private profile exists is in the edit private profile. I think that if a user that didn't have a private profile try to go to edit basic profile or public profile, we should redirect to the edit private profile.

**Comment by Nazeeh21** [comment]
Yeah I'm getting it. According to the current workflow, any new/existing user will try to edit the data, then they'll be redirected to the Private profile page and without saving the private profile, they won't be allowed to edit the basic/public profile.

So i think that we need to change the workflow for the existing users and allow them to proceed to edit the basic and public profile without saving the private profile.

**Comment by Nazeeh21** [comment]
Currently, for any user we are not allowing to edit the basic or public profile without saving the private profile.
So for the existing users only (whose private profile data exists), I'll add a button which will allow them to proceed for editing the basic profile without saving private profile

**Comment by damianmarti** [comment]
@Nazeeh21 Lets do it for the existing users only (whose private profile data exists):

- Make links for the step titles **1 - Private Profile**, **2 - Public Profile** and **3 - Basic Profile**, so the user can go to the edit profile section that he wants.
- Add in **Private Profile** and **Public Profile** sections a new button **Next**, that is just a link to the next section.

Please, let me know if is it clear now?

**Comment by Nazeeh21** [comment]
Got it, thanks 😊
