### ISSUE TITLE
Change node version spec to `>=14`

### ISSUE THREAD

**Issue by Dhaiwat10** [moonshotcollective/recruiter.party#83]
We should change the node version spec everywhere in the repo to `>=14` instead of `14` so that we can continue working on Node v16 locally and the deployments can use v14.

**Comment by Dhaiwat10** [comment]
Closed via #82

**Comment by damianmarti** [comment]
Reopened because the change was missing in some places. PR created https://github.com/moonshotcollective/recruiter.party/pull/84
